# Makefile for week09

all:	mutex_example timedwait

mutex_example:
	gcc -o mutex_example mutex_example.c -lpthread

timedwait:
	gcc -o timedwait timedwait.c -lpthread

clean:
	rm -f mutex_example  timedwait
